#!/bin/bash

TEST_NUM=3
TEST_MIN_INTERVAL=5
REPORT_INTERVAL=1
TEST_LENGTH=60

if [ -z "$1" -o -z "$2" ]; then
	echo "Arguments: <iperf_server> <out_dir>"
	exit 1
fi

IPERF_SERVER=$1
OUT=$2

mkdir -p "$OUT"

runTest() {
	FLAGS="-i $REPORT_INTERVAL -t $TEST_LENGTH"
	proto=$1
	if [ "$proto" == "UDP" ]; then
		FLAGS="$FLAGS -u -c"
	elif [ "$proto" == "TCP" ]; then
		FLAGS="$FLAGS -c"
	else
		echo "runTest() argument required!"
		return
	fi

	echo -n "Running $proto test $i..."
	iperf $FLAGS $IPERF_SERVER > $OUT"/"$2"_"$proto
	echo " done"
}

wait() {
	mins=$1
	while [ $mins -gt 0 ]; do
		echo "$mins minutes until next test set"
		sleep 60
		mins=$((mins-1))
	done
}

i=1
while [ $i -le $TEST_NUM ]; do
	runTest TCP $i
	runTest UDP $i
	i=$((i+1))
	if [ $i -lt $TEST_NUM ]; then
	    wait $TEST_MIN_INTERVAL
	fi
done
