#!/bin/bash

sysctl -w net.ipv4.conf.all.accept_source_route=1
sysctl -w net.ipv4.ip_forward=1
iptables -t nat -A POSTROUTING -o br0 -j MASQUERADE
iptables -t nat -A POSTROUTING -o br1 -j MASQUERADE

sysctl -w net.ipv6.conf.all.forwarding=1
iptables -t nat -A POSTROUTING -o br06 -j MASQUERADE
iptables -t nat -A POSTROUTING -o br16 -j MASQUERADE
