#!/bin/bash

source include

setSysVars net.ipv4.conf accept_source_route 1
sysctl -w net.ipv4.ip_forward=1
iptables -t nat -A POSTROUTING -o br0 -j MASQUERADE
iptables -t nat -A POSTROUTING -o br1 -j MASQUERADE

setSysVars net.ipv6.conf accept_source_route 1
setSysVars net.ipv6.conf forwarding 1
iptables -t nat -A POSTROUTING -o br06 -j MASQUERADE
iptables -t nat -A POSTROUTING -o br16 -j MASQUERADE
