#!/bin/bash

function iptables_rules {
	iptables $1 FORWARD -j IPOPTSTRIP $2
}

cd ~/xt_IPOPTSTRIP/xt_IPOPTSTRIP
iptables --flush
rmmod xt_IPOPTSTRIP
modprobe x_tables
insmod xt_IPOPTSTRIP.ko
iptables_rules -A $@
