#!/bin/bash

MOD_OPTS=$@

function iptables_rules {
	iptables $1 FORWARD -j IPOPTSTRIP $MOD_OPTS
}

cd ~/xt_IPOPTSTRIP/xt_IPOPTSTRIP
iptables_rules -D
rmmod xt_IPOPTSTRIP
modprobe x_tables
insmod xt_IPOPTSTRIP.ko
iptables_rules -A
