#!/bin/bash

source ../include/sys-vars

setSysVars net.ipv4.conf accept_source_route 1
sysctl -w net.ipv4.ip_forward=1

setSysVars net.ipv6.conf accept_source_route 1
setSysVars net.ipv6.conf forwarding 1
