#!/bin/bash

ROOT="../.."
KERNEL="$ROOT/bzImage"
BRIDGES="br0 br1 br06 br16"

DEBUG=0
while [ ! -z "$1" ]; do
    if [ "$1" == "-d" ]; then
		echo "GDB server enabled on 2nd instance"
		DEBUG=1
    else
		KERNEL="$1"
    fi
    shift
done

function start {    
    qemu-system-x86_64 -hda "$1" -kernel "$KERNEL" -append "root=/dev/sda1" -net nic,macaddr=52:54:00:12:$((RANDOM%50)):$((RANDOM%50)) -net tap,ifname="$2",vlan=0,script=no,downscript=no -net nic,macaddr=52:54:00:12:$((RANDOM%50)):$((RANDOM%50)) -net tap,ifname="$3",vlan=0,script=no,downscript=no &
    echo "$1 QEMU PID: $!"
}

for bridge in $(echo $BRIDGES); do
    if [ -z "$(ifconfig | grep $bridge)" ]; then
		sudo ifup $bridge
    fi
done

start "$ROOT/images/debian-wheezy-1.img" "tap0" "tap06"

if [ $DEBUG -eq 1 ]; then
    COMMAND="$COMMAND -s -S"
fi
start "$ROOT/images/debian-wheezy-2.img" "tap1" "tap16"
