#!/bin/bash

# Launch a script in an xterm window
# $1 - Script
# $2 - Window title

if [ -z "$1" ]; then
    echo "Arguments: <script>"
    echo "Options: <window_title>"
    exit 1
fi

title="$2"
if [ -z "$2" ]; then
    title="launch"
fi

xterm -title $title -hold -e "$1;echo;echo Close window"  &
